# Generated by Django 4.0.4 on 2022-04-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=40)),
                ('term_min', models.PositiveSmallIntegerField()),
                ('term_max', models.PositiveSmallIntegerField()),
                ('rate_min', models.FloatField()),
                ('rate_max', models.FloatField()),
                ('payment_min', models.IntegerField()),
                ('payment_max', models.IntegerField()),
            ],
        ),
    ]
