# Generated by Django 4.0.4 on 2022-04-27 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=40)),
                ('term_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('term_max', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('rate_min', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('rate_max', models.FloatField(validators=[django.core.validators.MaxValueValidator(100.0)])),
                ('payment_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ('rate_min',),
            },
        ),
    ]
