# Generated by Django 4.0.4 on 2022-04-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
