# Generated by Django 4.0.4 on 2022-04-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('payment',)},
        ),
    ]
