# Generated by Django 4.0.4 on 2022-04-24 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_offer_options_remove_offer_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='payment_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='payment_min',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='rate_max',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='rate_min',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
